### ISSUE TITLE
https://promactslack.azurewebsites.net/ is not working.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#100]
@iamronakshah 

Steps to be followed:

1) Open a link (https://promactslack.azurewebsites.net/)
2) Then click on login with promact.
3) Then you may see the page is loading when you console you may see the error.

Please refer the screenshot. 

![image](https://cloud.githubusercontent.com/assets/20476866/19337748/74635592-9135-11e6-85b0-627ab0b5dd6e.png)

**Comment by chintans** [comment]
@hardikbhatt which credentials did you used to login?

**Comment by hardikbhatt** [comment]
Sir these are the credentials i have used for login.

Username: roshni@promactinfo.com
Password: Admin@123

**Comment by iamronakshah** [comment]
Sir I have checked on dev branch ,it's working fine with same login credentials.
Please check whether new changes are reflected on live.
