### ISSUE TITLE
List of Team Members and Team Leader are not in alphabetical order.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#102]
@iamronakshah 

Steps tp be followed:

1) Open a live link (https://promactoauth.azurewebsites.net)
2) Click on Project tab.
3) Click on Add Project.
4) When you select "List of Team Members" and "List of Team Leader", you may see they are not arranged in alphabetical order.

Please see the screenshot.

![2016-10-13_12-33-23](https://cloud.githubusercontent.com/assets/20476866/19339532/9671cf5e-9141-11e6-8476-de29a01d3fde.png)

![2016-10-13_12-34-26](https://cloud.githubusercontent.com/assets/20476866/19339533/969b5df6-9141-11e6-8eab-c3cb567bb4ce.png)

**Comment by iamronakshah** [comment]
I have updated my logic now you can see the List of Team Members in alphabetical order.
