### ISSUE TITLE
Time is not in proper format and Title "Time" is missing.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#103]
@iamronakshah 

Steps to be followed:

1) Open a live link (https://promactoauth.azurewebsites.net)
2) Click on Projects tab.
3) Then you may see the added projects in that date and time is not in proper format and even the time is been missing from the title. 

Please see the screenshot.

![2016-10-13_14-39-37](https://cloud.githubusercontent.com/assets/20476866/19343321/64433a60-9153-11e6-9fc8-76218e8043b0.png)

**Comment by iamronakshah** [comment]
I have updated my logic once uploaded then after you can see only Created date and Updated date.
