### ISSUE TITLE
Move environment variables to appsettings

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#112]
Best practice for .Net core application is to have sensitive information in appsettings. Please move all sensitive information to appsettings utilising best practices described by .net core documentation.

https://docs.asp.net/en/latest/fundamentals/configuration.html

**Comment by chintans** [comment]
@ankit213 this task needs to be done by you

**Comment by ankit213** [comment]
ok, but I will start after lunch break

**Comment by ankit213** [comment]
Start Work With : 15-10-2016 10:34 
Estimate Time :  3 Hours

**Comment by ankit213** [comment]
Completed issue but not committed in dev branch
