### ISSUE TITLE
Improve build time

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#114]
Right now we are using deploy.cmd to deploy code. This file uses MsBuild to build and deploy dotnet core project. Ideally, we should move away from MSBuild and use dotnet build command. Currently it takes about 2000 seconds or 30 min approx for every build. It should be somewhere near to 2 to 4 min. Prepare a plan on how to improve this and implement it.

**Comment by iamronakshah** [comment]
Started Work on 20-10-2016 
Estimate Time : 5 Hours

**Comment by iamronakshah** [comment]
I have updated deploy.cmd removed MSBUILD_PATH command and added dotnet build , dotnet publish commands. yet not uploaded on dev.

**Comment by chintans** [comment]
error: D:\home\site\repository\promact-oauth-server\Promact.Oauth.Server\src\Promact.Oauth.Server
Failed exitCode=1, command=dotnet restore "D:\home\site\repository\promact-oauth-server\Promact.Oauth.Server\src\Promact.Oauth.Server"
Couldn't find 'project.json' in 'D:\home\site\repository\promact-oauth-server\Promact.Oauth.Server\src\Promact.Oauth.Server'
Failed exitCode=1, command=dotnet build "D:\home\site\repository\promact-oauth-server\Promact.Oauth.Server\src\Promact.Oauth.Server" --output "D:\local\Temp\8d3f904c9248384"  --configuration Release --framework netcoreapp1.0
An error has occurred during web site deployment.

**Comment by chintans** [comment]
This is the error that came from server

**Comment by iamronakshah** [comment]
I have updated dotnet commands path in deploy.cmd.
