### ISSUE TITLE
In "View Project" list of team members are not in alphabetical order.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#119]
Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on Project tab.
3) Click on view button.
4) Then you may see List of Team Members is not in alphabetical order.

Please see the screenshot.
![2016-10-18_10-19-27](https://cloud.githubusercontent.com/assets/20476866/19464928/e9c30472-951d-11e6-9ebf-8c81d18c8073.png)

**Comment by iamronakshah** [comment]
Estimated Time - 30 Minutes
Estimated Completion Date - 18/10/2016

**Comment by iamronakshah** [comment]
I have updated my logic now onwards list of team members are in alphabetical order.
