### ISSUE TITLE
Change password is not working

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#121]
Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on Change Password tab.
3) Enter the details as
              **a) Old Password: Admin@123
              b) New Password: 123456789@a
              c) Re-Enter New Password: 123456789@a**
4) Then click on **"Change"** button.
5) You may see the toaster message **"Password Changed Successfully"**.
6) Then Logout from the site.
7) Again login with the same link (https://promactoauth.azurewebsites.net).
8) Then enter the following things:
              **a) Email: roshni@promactinfo.com
              b) Password: 123456789@a**
9) It will show an error **"Invalid login attempt"**
10) Then enter the old password **"Admin@123"** it will login into the site.

New Password and Re-Enter New Password must be according to the Password Standards (i.e Alphanumeric, Symbols etc)

**Comment by ankit213** [comment]
Start Work : 20-10-2016 10:46
Estimated Time : 1 Hours

**Comment by ankit213** [comment]
Issue Resolved but not on Dev branch.

**Comment by ankit213** [comment]
Finished Date : 20-10-2016
