### ISSUE TITLE
Error after login 

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#125]
When I tried login with following credentials. It showed me following error.

username: chintanshah@promactinfo.com
password: User00_EEHEBDEE

Exception:

Url: https://promactoauth.azurewebsites.net/OAuth/Login

{"message":"A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.","stackTrace":"   at Promact.Oauth.Server.Data_Repository.DataRepository`1.Add(T entity) in D:\\home\\site\\repository\\Promact.Oauth.Server\\src\\Promact.Oauth.Server\\Data Repository\\DataRepository.cs:line 59\r\n   at Promact.Oauth.Server.Repository.OAuthRepository.OAuthRepository.OAuthClientChecking(String email, String clientId) in D:\\home\\site\\repository\\Promact.Oauth.Server\\src\\Promact.Oauth.Server\\Repository\\OAuthRepository\\OAuthRepository.cs:line 67\r\n   at Promact.Oauth.Server.Repository.OAuthRepository.OAuthRepository.<UserNotAlreadyLogin>d__13.MoveNext() in D:\\home\\site\\repository\\Promact.Oauth.Server\\src\\Promact.Oauth.Server\\Repository\\OAuthRepository\\OAuthRepository.cs:line 110\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Promact.Oauth.Server.Controllers.OAuthController.<Login>d__7.MoveNext() in D:\\home\\site\\repository\\Promact.Oauth.Server\\src\\Promact.Oauth.Server\\Controllers\\OAuthController.cs:line 80\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()"}

**Comment by ankit213** [comment]
I have checked , it's working on my PC using this credential 
username: chintanshah@promactinfo.com
password: User00_EEHEBDEE

Please Clear Cache and try to again.

**Comment by ankit213** [comment]
Started Issue : 20-10-2016 16:09
Estimated Time: Try to complete EOD

**Comment by chintans** [comment]
It is now redirecting on localhost, The issue is not resolved
