### ISSUE TITLE
Error while switching tab

### ISSUE THREAD

**Issue by ghost** [Promact/promact-oauth-server#126]
Scenario 1:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Login with following credentials:

Email: hardik@promactinfo.com
Password: User00_FHGFDACB

3) Then you may see the detail page of the respective user.
4) Then click on project tab you will get an error.

Please refer the screenshot:

![2016-10-20_16-17-53](https://cloud.githubusercontent.com/assets/20476866/19557133/02d6d3f6-96e2-11e6-98c1-19b2b41ba198.png)

Scenario 2:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Login with following credentials:

Email: hardik@promactinfo.com
Password: User00_FHGFDACB

3) Then you may see the detail page of the respective user.
4) then click on User tab you may see the error.

Please refer the screenshot:

![2016-10-20_16-12-55](https://cloud.githubusercontent.com/assets/20476866/19557152/2273e87a-96e2-11e6-9877-46c6e77eb211.png)

Please try to solve these issues first as its roadblock for me as I am not able to move on with further testing.

**Comment by ankit213** [comment]
Started Work : 21-10-2016 11:30
Estimated Time : 6 Hours
Finished Date : 22-10-2016

**Comment by iamronakshah** [comment]
Started Work : 21-10-2016 11:45
Estimated Time : 6 Hours 30 min
Finished Date : 22-10-2016
