### ISSUE TITLE
integrate ng2-admin for admin panel

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#137]
Integrate ng2-admin design within current site

https://github.com/akveo/ng2-admin

**Comment by juliepromact** [comment]
By integration, did you mean to apply the design changes to existing pages too ?

**Comment by juliepromact** [comment]
Start Date : 25-10-2016 18:00
Estimated Time : 80 Hours
End Date : 15-11-2016

**Comment by chintans** [comment]
Not to be integrated
