### ISSUE TITLE
Email field is not working proper.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#138]
Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Enter the credentials as

**a) Email: roshni@promactinfo.com
b) Password: Admin@123**

3) Click on User tab.
4) Click on Add New User.
5) Enter the following details as

**a) First Name: Testing
b) last Name: 123
c) Email: testing@gmail.com
d) Slack username: test
e) User Role; Employee
f) Date of Joining: 27/06/2016**

6) Then click on Add button you may see the error as "Username Already Exists" now change the toaster message as "Email is invalid".

**Note: Email must not allow other domain to register other than promactinfo.com

**Comment by ankit213** [comment]
Started Date :25-10-2016
Estimated Time: 2 Hours 30 min

**Comment by ankit213** [comment]
Completed Task but not in dev branch.
