### ISSUE TITLE
show all registered and active users in Team Leader and Team Member drop down

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#145]
right now only employee role is shown in both dropdowns. It should display all active users

**Comment by iamronakshah** [comment]
Start Date : 27-10-2016
Estimation : 30 min
Finish Date : 27-10-2016

**Comment by iamronakshah** [comment]
Updated User Repository now onwards users can see the all the active user in both dropdowns

**Comment by hardikbhatt** [comment]
@chintans this is been checked on live you may close the issue.
