### ISSUE TITLE
Remove spacing from the name field when it is created or modified.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#149]
When any user is been created or modified we must remove the unnecessary spacing from it. Interm trim the name and save it.

It is been affected in the project side as the List of Team Leader and Team Members are been not in proper order. When any spacing is been used in the name field.

**Comment by iamronakshah** [comment]
Start Date : 28-10-2016
Estimation : 30 min
Finish Date : 28-10-2016

**Comment by iamronakshah** [comment]
I have Updated user-add.component and user-edit.component. so now onwards unnecessary spacing are remove the when user are created or modified.
