### ISSUE TITLE
add gulp task to run client side unit test on travis ci

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#15]
Create a gulp task like 'test-ci' which should execute test cases in a CI environment with travis as reporter.

**Comment by ankit213** [comment]
Completed integration but Right Now not Working because of  Changed Anguler2 Version
(Try to solve above issue but some are remaining like TestConnection issue and MD2 related issue)

**Comment by ankit213** [comment]
Worked on try to solve client side test case issue in updated angular version 2.0.0 but it's not working in local so I didn't complete my this task

**Comment by ankit213** [comment]
completed travic-ci implement with latest anguler version 2.0.0
