### ISSUE TITLE
add client side code coverage tool

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#16]
integrate client side code coverage tool like [Istanbul](https://github.com/gotwarlost/istanbul) and link that with coveralls.

**Comment by chintans** [comment]
is this feature completed since it is marked as review?

**Comment by ankit213** [comment]
its completed but in dev branch it's not merged so it is marked as review.

**Comment by ankit213** [comment]
I try to solve this issue using below link "https://github.com/caitp/karma-coveralls", In this link I have referred 'repo_token' set to in 'ENV VARIABLE'/'YAML VARIABLE'/'KARMA VARIABLE'. But there is any given note, "Please note that it is NOT recommended to save your report token in plain text for everyone to see" so don't understand how to encrypt that token. So I try to find how to encrypt but don't find the proper way

**Comment by ankit213** [comment]
I have generate environment variable also and set in travis.yml file but there are no any files displays in coveralls , I try to check my configuration but not find any solution.

**Comment by chintans** [comment]
What is the status for this task? This task is in progress for over a month now.

**Comment by ankit213** [comment]
Sir, I was told about this issue ,I can't  find any proper solution , there is roadblock, because I followed all steps in given links 
https://github.com/gotwarlost/istanbul
https://github.com/caitp/karma-coveralls 
Locally coverage folder is created and also generated reports but not generated coverage in coveralls.

**Comment by chintans** [comment]
Please don't keep discussion verbal. Write your roadblocks here so I can understand what exactly are you facing as a roadblock.

**Comment by ankit213** [comment]
sir, I think i was tell this thinks in slack discussion, i was added below code and also added coveralls secure key in travis.yml but not genrated coverage in covealls , 
after_success:
  - cat ./coverage/coverage-final.json | ./node_modules/coveralls/bin/coveralls.js

There are no errors generated and build is succesfull in travis-ci also run above command but i think some missing in converalls configuer, I have checked in https://coveralls.io site but did not find any proper documentation.

**Comment by chintans** [comment]
The description above just conveys the scenario. Not roadblock. Please explain clearly what are your roadblock. For example Is cat command your roadblock?

**Comment by ankit213** [comment]
No sir,Cat Command is Working on Travis but I used this new command  " - ./node_modules/.bin/istanbul cover --report lcov node_modules/.bin/jasmin test/"
 in script section in Travis.yml but its throw error "no such find file and directory"
