### ISSUE TITLE
update yarn integration for travis

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#190]
installing yarn from npm is deprecated and needs to be updated as per below methods.

1. https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
2. https://yarnpkg.com/en/docs/install#linux-tab

Option 1 is preferable. If it does not workout option 2 will work. This is a high priority item as unless this is fixed other pull request will not build in travis.

**Comment by ankit213** [comment]
Start Date: 13-12-2016
Estimated Time : 2 Hours
End Date: 14-12-2016
