### ISSUE TITLE
Restructure OAuth External Login Flow

### ISSUE THREAD

**Issue by siddharthashw** [Promact/promact-oauth-server#207]
Right now its not flowing the rule of OAuth 2.0 flow. So I need to restructure the OAuth flow and implement flow as OAuth 2.0 rules.

Following this link - https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2

This is the current flow:

1.	When user click the link, Login with Promact, then it will call the point 2
2.	Authorization Code Link : The above link call a API and it will redirect to https://promactoauth.azurewebsites.net/OAuth/ExternalLogin?clientId=PromactAppClientId
3.	User Authorizes Application : After successfully completion of point 2, server will redirect to OAuth server. In OAuth checking of app details with clientId will be done then user need to login.
4.	OAuth Request to Application :  After successfully completion of point 3, An request(server side call) will be send from OAuth to application with refresh token for getting app’s secret and redirect Uri then OAuth will receive the response and check for app secret.
5.	Application Receives User Details and Access token : After successfully completion of point 4, Application will receive user details and add user to application and store the data.

My proposal for new structure:

1.	When user click the link, Login with Promact, then it will call the point 2.
2.	Authorization Code Link : The above link call a API and it will redirect to
https://promactoauth.azurewebsites.net/OAuth/ExternalLogin?clientId=PromactAppClientId&redirectUri=redirectUri
Example:
https://promactoauth.azurewebsites.net/OAuth/ExternalLogin?clientId={PromactAppClientId}&redirectUri=”https://promactslack.azurewebsites.net/OAuth/Authorization?code={AuthorizationCode}”
PromactAppClientId = Promact app’s client Id
redirectUri = external login call Url 
3.	User Authorizes Application : After successfully completion of point 2, server will redirect to OAuth server. In OAuth checking of app details with clientId and redirectUri will be done then user need to login.
4.	Application Receives Authorization Code : After successfully completion of point 3, server will redirect to
Point 2’s redirectUri  with authorization code.
Example : https://promactslack.azurewebsites.net/OAuth/Authorization?code=DFSD45FGD45FG11
5.	Application Requests Access Token : After successfully completion of point 4, Server will call a API and application will request the OAuth for access token and user details
Http Request Url will be like this
https://promactoauth.azurewebsites.net/OAuth/AccessToken?clientId=PromactAppClientId&authorizationcode=AuthorizationCode&clientSecret=PromactAppClientSecret
Example :
https://promactoauth.azurewebsites.net/OAuth/AccessToken?clientId={PromactAppClientId}&authorizationcode={AuthorizationCode}&clientSecret={PromactAppClientSecret}
PromactAppClientId=Promact app’s clientId
AuthorizationCode  = Point 4 code
PromactAppClientSecret – Promact app’s client secret
6.	Application Receives Access Token : After successfully completion of point 5 and authorization code, client secret and details match then, Application will receive all required details of user and create and user for external login and store its access token of Promact.

**Comment by chintans** [comment]
Write down the flow that you sent me over email

**Comment by siddharthashw** [comment]
added the flow, which i sent to you over email

**Comment by siddharthashw** [comment]
Start Date - 07/12/2016
End Date - 9/12/2016
Estimated Time - 8 hours

**Comment by chintans** [comment]
hold on this implementation

**Comment by chintans** [comment]
Since we are re-writing this flow. It would be advisable to explore other option which can improve future maintenance.

Please review this library that already has all OAuth 2 flow built in. We should be using this

https://github.com/IdentityServer/IdentityServer4

**Comment by chintans** [comment]
Documentation - https://identityserver4.readthedocs.io/en/release/

**Comment by siddharthashw** [comment]
I need time to anlaysis about the IdentityServer4. Already started reading.

**Comment by siddharthashw** [comment]
We are going to use IdentityServer4 for OAuth implementation. We will use openId authentication for authentication and identity server authentication for authorization. 

Flow : 
1. When user click the link, Login with Promact, then it will call the point 2
2. It will pass the access to UseOpenIdConnectAuthentication and there we have set authorization base uri(OAuth base uri). Then it will be redirect to OAuth server for authentication.
3. After successfully completion of point 2, User need to provide there credential of OAuth on login page.
4. If User's credential match with database details then it will ask to user to approve the scope it added to pass.
5. Then it will redirect to Application.
6. After successfully completion of point 4,  Application will receive a access token, refresh token.
7. For user details like user’s Id, email and slackUserId, we will use UserInfoEndPoint. From that details we will add user details in our application.
8. For User details, we will use user Id to get user details, and for authorization we will use access token.
9. And then will save the user details in Application.

Note:- 
Access token life scope will be of 1 day(24 hours)
Refresh token life scope will be of 60 days(1440 hours)

Here is the flow in diagram: 
![identityserver4flow](https://cloud.githubusercontent.com/assets/16556606/22063141/43d5d962-dda3-11e6-9040-7c546432fd87.png)

**Comment by siddharthashw** [comment]
@chintans and @rushi216 please check the flow and provide the feedback.
