### ISSUE TITLE
Fix this build time warning

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#209]
/app/UserController.cs(261,38): warning CS0168: The variable 'ex' is declared but never used
/app/UserController.cs(305,33): warning CS0168: The variable 'ex' is declared but never used
/app/UserController.cs(309,30): warning CS0168: The variable 'ex' is declared but never used
/app/UserController.cs(374,30): warning CS0168: The variable 'ex' is declared but never used
/app/UserController.cs(392,38): warning CS0168: The variable 'ex' is declared but never used

**Comment by ankit213** [comment]
Already solved this issue in pull request #195.
