### ISSUE TITLE
Load 3rd Party libraries over CDN in production

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#210]
right now static resources such as Bootstrap, Jquery and other 3rd party libraries are loaded from application root itself. We need to configure the page in such a way that on production it loads these libraries from CDN and on local/development it loads from the local folder.

Here is the link for suggested approach.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments

**Comment by ankit213** [comment]
Start Date: 18-01-2017
Estimated Time : 6 Hours
End Date: 18-01-2017

**Comment by chintans** [comment]
6 hours is too high. it is matter of 1 or 2 hours only

**Comment by ankit213** [comment]
Actually, I had no idea about this so I had given more time for analysis, but now I have an idea about this so I will complete within 2 Hours.
