### ISSUE TITLE
regenerate auth id and auth secret

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#245]
not able to regenerate auth id and auth secret on production url oauth.promactinfo.com. it throws 500 on browser console.

**Comment by chintans** [comment]
{"message":"Object reference not set to an instance of an object.","stackTrace":"   at Promact.Oauth.Server.Repository.ConsumerAppRepository.ConsumerAppRepository.GetRandomNumber(Boolean isAuthId) in /app/Repository/ConsumerAppRepository/ConsumerAppRepository.cs:line 129\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()"}

**Comment by siddharthashw** [comment]
This is a issue of string literal is not load on runtime. That functionality of string literal is done by @iamronakshah . So he will be able to tell why it's return null from string literal.

**Comment by siddharthashw** [comment]
Issue - #144 . Is still goes on.

**Comment by siddharthashw** [comment]
Fixes
