### ISSUE TITLE
creating consumer apps to validate consumers who can access to the system

### ISSUE THREAD

**Issue by iroshni** [Promact/promact-oauth-server#3]

**Comment by ankit213** [comment]
I had completed consumer-app functionality in oauth-server-project..

**Comment by chintans** [comment]
@hardikbhatt have you tested this feature?

**Comment by hardikbhatt** [comment]
Yes, i have tested this feature on live and we are able to create a Consumer app. 
Once ERP issue is solved I can use the Auth ID from the consumer app.

**Comment by hardikbhatt** [comment]
The issue has been solved it is working on live.
