### ISSUE TITLE
Upgrade to latest Angular 2.0 release version

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#34]
Update project to target latest AngularJS 2.0 version. identify changes in code and list out here. we will assign work to respective members accordingly.

**Comment by siddharthashw** [comment]
I have upgraded the version of angular to the latest version. And Right now Md2 and toaster are not working. And I have commented the client side test cases. and check for normal working. It's working and stable now. All need to update their test cases. Once md2 will launch for angular latest version. I will update the project.
