### ISSUE TITLE
hard coded values of number of leaves

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#35]
Values of Sick leave and casual leave is hard coded in the application. It should come from the database.

**Comment by iamronakshah** [comment]
Am I supposed to make UI for capturing number of sick leave and casual leave or simply add it to database through seed?

**Comment by iamronakshah** [comment]
Sir please suggest me which flow i have to follow for the sick leave and  casual leave values.

**Comment by iamronakshah** [comment]
I have use the app setting for the sick leave and casual leave hard coded values
