### ISSUE TITLE
Update test cases as per angular 2.0.0

### ISSUE THREAD

**Issue by siddharthashw** [Promact/promact-oauth-server#40]
You need to update your all test cases and mock files as per required in angular 2.0.0

**Comment by ankit213** [comment]
worked with ronak on analysis and update about client side test case in anguler latest version.
done with simple test case now issue is genrated with own project component so try to solve this issue.

**Comment by iamronakshah** [comment]
Me and Ankit updated Kama.config and karma.shim files and started project component test cases.

**Comment by iamronakshah** [comment]
Updated karma.shim file and start project module test cases

**Comment by iamronakshah** [comment]
Updated the karma.config file and also Updated project module test cases.

**Comment by iamronakshah** [comment]
Updated test cases in project module and all related mock files are updated.now i am working on user module test cases.

**Comment by ankit213** [comment]
Completed Consumer App and Change Password Module Client Side Test Cases , Now Only "User Module" is remaining , Ronak is working on it.

**Comment by iamronakshah** [comment]
Completed User Module test cases.
