### ISSUE TITLE
In "Add Projects" title is wrong.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#50]
@ankit213 

Steps to be followed:

1) Open Promact Oauth link (https://promactoauth.azurewebsites.net)
2) Click on Project Tab.
3) Click on "Add Projects"
4) You can see the title as "**USERS**" it must be "**PROJECTS**"

Please see the screenshot for more reference.
![projects](https://cloud.githubusercontent.com/assets/20476866/18903479/0ec6edf8-8577-11e6-9598-68a2e1467b7c.png)

**Comment by iamronakshah** [comment]
Updated Add Project title.
