### ISSUE TITLE
In "User Edit" page back button is not proper.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#51]
@ankit213 

Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on User tab.
3) Click on Edit button on anyone of the user.
4) Then you may see back button it is not same as others page.

Please refer screenshot.

![user edit back button](https://cloud.githubusercontent.com/assets/20476866/18903638/d3442fd8-8577-11e6-8987-faa1206a96c3.png)

![2016-09-28_12-32-55](https://cloud.githubusercontent.com/assets/20476866/18903643/ddb8cf28-8577-11e6-97c9-5bf890a220b8.png)

**Comment by iamronakshah** [comment]
Updated back button in user module.
