### ISSUE TITLE
In "Add Consumer" there is no back button.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#52]
@ankit213 

Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on Consumer App tab.
3) Click on "Add a New App".
4) There is no back button on the top right-hand

Please refer the screenshot:

![consumer app back](https://cloud.githubusercontent.com/assets/20476866/18904014/b976faac-8579-11e6-824f-63b051fcf7f8.png)
 side.

![2016-09-28_12-32-55](https://cloud.githubusercontent.com/assets/20476866/18904034/d0fbdcce-8579-11e6-8462-610632f866fb.png)

**Comment by iamronakshah** [comment]
Added back button in Consumer module
