### ISSUE TITLE
Change Password is not working.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#53]
@ankit213 

Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on Change Password tab.
3) Enter the Old Password in Password.
4) Enter the same old password in "New Password" and in "Confirm Password" also.
5) Then click on change button. The password will be changed.

Please refer the video which I have sent you in slack personally.

**Comment by ankit213** [comment]
completed this bug but right now not in dev branch
