### ISSUE TITLE
Tab Switching issues.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#54]
@iamronakshah 

Steps to be followed:
1) Open a link (https://promactoauth.azurewebsites.net)
2) Then click on various tabs continuously do it for 2 to 3 times then leave the mouse you may see the tab switching automatically.

Please see the video which I am sending you in slack personally.

**Comment by iamronakshah** [comment]
Yesterday I have updated routing but i have facing same problem.

**Comment by iamronakshah** [comment]
Tab Switching issue solved. i have added loader in project module and user list page. 
So please test it from your side and let me know if any changes are required.

**Comment by iamronakshah** [comment]
Estimated Time - 4 Hours 
Estimated Completion Date - 20/10/2016

**Comment by iamronakshah** [comment]
I have removed getRole method in user module , app component and project list component. now user role fetch in userrole model. in local it works fine. So please test it from your side and let me know if any changes are required.

**Comment by hardikbhatt** [comment]
Working fine on live.
