### ISSUE TITLE
"Add User" Email field is not working properly.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#55]
@ankit213 

Steps to be followed:
1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on User tab.
3) Click on Add User.
4) Then Enter the details (Firstname, Lastname, Email and slack Username)
5) Then Click on Add button you may see "**@promactinfo.com**" is been added when you click on Add button.

Please refer the video which is been sent to you personally.

**Comment by ankit213** [comment]
completed this bug but right now not in dev branch
