### ISSUE TITLE
"Add User" Toaster message is wrong.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#56]
@ankit213 

Steps to be followed:
1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on User tab.
3) Then click on Add Button.
4) The toaster message on the top right-hand side says "Slack User Name Already Exists"

Please refer the screenshot.

![last name error](https://cloud.githubusercontent.com/assets/20476866/18907953/5c9babb8-858b-11e6-90c7-1ec7f4f94620.png)

![2016-09-27_11-59-07](https://cloud.githubusercontent.com/assets/20476866/18907954/5caa2120-858b-11e6-93c8-c9798c8a0ebc.png)

**Comment by ankit213** [comment]
completed this bug,but right now not in dev branch
