### ISSUE TITLE
In "Consumer App" Submit button is not clickable and no Error message also.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#57]
@ankit213 

Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on Consumer App.
3) Click on Add a New App.
4) Do not enter any details just click on submit button.
5) The button is not clickable.
6) We are not able to find out the error messages also.
7) Do it same as User and Project.

**Comment by ankit213** [comment]
completed this bug, but right now not in dev branch
