### ISSUE TITLE
In " Edit Projects" Users List is not been seen.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#58]
@ankit213 

Steps to be followed:
1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on Project tab.
3) Click on Edit in any one of the projects.
4) Users list is not been seen in the edit page.
5) If we want to delete or add any user then how come will we delete or add any user.

Please refer the screenshot.

![edit projects](https://cloud.githubusercontent.com/assets/20476866/18908814/c056bc08-858e-11e6-97ed-3d12a00085c2.png)

**Comment by iamronakshah** [comment]
I have solved this issue this morning. please test it from your side and please let me know if any changes is required.
