### ISSUE TITLE
Do not use any static class or methods unless required absolutely

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#70]
Do not use any static class or methods unless required absolutely. Using static class creates an issue for Unit testing. So, String constants, environment variables and any other equivalent utility classes should also be not static.

**Comment by ankit213** [comment]
Yes Sir, 
Mostly in OAuth project string constant class and environment variables are non-static but still I will check.

**Comment by iamronakshah** [comment]
i didn't used any static class and method in Oauth project

**Comment by chintans** [comment]
@iamronakshah Please ensure there are no static class or static property class in the entire project.

**Comment by iamronakshah** [comment]
Started Work on 17-10-2016 11:00 
Estimate Time : 1 Hours 30 mints
