### ISSUE TITLE
In "View Project" list of team members are not fully seen.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#72]
@iamronakshah 

Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on Project tab.
3) Click on View Project.
4) In List of Team Members you are able to see only 3 names as there are 6 team members, rest of the team members are not seen.

Please see the screenshot.

![edit project](https://cloud.githubusercontent.com/assets/20476866/19063288/0d91396e-8a1f-11e6-824a-79d0f4e778d5.png)

![view project](https://cloud.githubusercontent.com/assets/20476866/19063301/23bcc884-8a1f-11e6-8434-2273775611aa.png)

**Comment by iamronakshah** [comment]
Updated Project-view.html.

**Comment by hardikbhatt** [comment]
Scenario 2:
Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on Project tab.
3) Click on View Project.
4) In "Team Leader" you may see a drop-down list. Which needs to be removed from the view.

Please see the screenshot.

![2016-10-07_14-33-10](https://cloud.githubusercontent.com/assets/20476866/19184527/3b80d590-8c9b-11e6-9c10-96ceee3a7ffd.png)

**Comment by iamronakshah** [comment]
I have updated the project view.html also fix the other bugs. but yet not uploaded on dev,
