### ISSUE TITLE
Implement NLog

### ISSUE THREAD

**Issue by ankit213** [Promact/promact-oauth-server#74]
Implement NLog in Oath Project using below link "https://docs.asp.net/en/latest/fundamentals/logging.html"

**Comment by chintans** [comment]
All internal logs of Microsoft assemblies are also logged. Please configure it to ensure that only our application related logs are logged.

**Comment by chintans** [comment]
Change the way log files are created. Now, It should create separate files for each verbosity. I.e., for information message there will be a different file, for error there will be a separate file and so on.
