### ISSUE TITLE
"Add User" Functionality is not working.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#91]
@ankit213 

Steps to be followed:

1) Open a live link (https://promactoauth.azurewebsites.net)
2) Click on User tab.
3) Click on Add User.
4) Enter the following details.
    A) First Name: qwerty
    B) Last Name: poiuy
    C) Email: vishal
    D) Slack Username: asdf
    E) User Role: Employee
    F) Date: 10/10/2016
5) Then click on Add button twice the User will be added successfully.
6) Already the Email has been register then also it is been saved.
7) The toaster message says **User is been added successfully**.

Please see the video which is been sent to you personally on slack.

**Comment by ankit213** [comment]
Completed Bug, Spent Time : 2 Hours
