### ISSUE TITLE
When we click on "Details" page we can see "Edit" button.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#92]
@ankit213 

Steps to be followed:

1)  Open a live link (https://promactoauth.azurewebsites.net)
2) Click on User Tab.
3) Then click on Details button you may see the Edit Button for 2 or 3 seconds and then it disappears after it.

Please see the video which is been sent to you personally on slack.

**Comment by ankit213** [comment]
Start With Issue 15-10-216 11:56 
Estimate Time : 1 Hour

**Comment by ankit213** [comment]
Solved issue but not committed in dev branch
