### ISSUE TITLE
In "User List" Register user are not in proper order.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#97]
@ankit213 

Steps tp be followed:

1) Open a live link (https://promactoauth.azurewebsites.net)
2) Click on user tab.
3) Click on Add User.
4) Enter all the details and click on add, You may see the added user will be seen in a random order so make it as new user will be seen at the top.

**Comment by ankit213** [comment]
Started work: 18-10-2016 10:25
Estimate Time: 15 min
