### ISSUE TITLE
Pagination is required in Users Tab.

### ISSUE THREAD

**Issue by hardikbhatt** [Promact/promact-oauth-server#99]
@ankit213 

Steps to be followed:

1) Open a link (https://promactoauth.azurewebsites.net)
2) Click on User tab.
3) You may see the list goes on, So for that we can add an pagination so it will be easy to scroll the pages.

**Comment by ankit213** [comment]
Started work: 18-10-2016 11:55
Estimated Time : 8 Hours

**Comment by ankit213** [comment]
tried to solve this issue using  "angular2-datatable" but there some errors so it's not completed if anyone has any idea about a third-party tool or repository for pagination and filter in angular2, please suggest.

**Comment by ankit213** [comment]
Resolved issue  but not in dev branch
